#-----------------------------------------------------------------------
#        Author: Aamnah
#          Link: https://aamnah.com
#       Version: 0.1.0
#          Date: 2021-02-26
#       Lastmod: 2026-04-24
#   Description: Yarn init defaults — license and version
# Compatibility: Debian, Ubuntu, Armbian, macOS
#-----------------------------------------------------------------------

# ~/.yarnrc.yml

initLicense: 'CC-BY-SA-4.0'
initVersion: '0.0.1'
